
// Generated by Cake
// using System.Reflection;

[assembly: System.Reflection.AssemblyVersion("4.2.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("4.2.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("4.2.0-alpha.0.17")]

