name: NUnit.Myget.Publish
env:
  MinVerAutoIncrement: minor
on:
  push:
    branches:
      - main
      - release/*
      - myget
  workflow_dispatch:
  

defaults:
  run:
    shell: pwsh
jobs:
  build-windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
    - name: ⤵️ Checkout Source
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 0

    - name: 🛠️ Setup .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
      with:
        global-json-file: global.json
        dotnet-version: |
            6.0.x
            8.0.x
        
    - name: 🛠️ Install dotnet tools
      run: dotnet tool restore

    - name: 🔨 Build and Test
      run: dotnet tool run dotnet-cake --target=Test --configuration=Release

    - name: 📦 Package
      run: dotnet tool run dotnet-cake --target=Package

    - name: 💾 Upload build artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: Package
        path: package

    - name: 💾 Upload test results
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: Test results (Windows)
        path: TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    - name: Publish nupkg and snupkg to Myget.org
      run: |
          foreach($file in (Get-ChildItem package -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.PUBLISHMYGET }}" --source https://www.myget.org/F/nunit/api/v3/index.json --skip-duplicate
          }

