name: NUnit.Nuget.Publish
env:
  MinVerAutoIncrement: minor
on:
  workflow_dispatch:
  

defaults:
  run:
    shell: pwsh
jobs:
  build-windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
    - name: ⤵️ Checkout Source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 🛠️ Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
        dotnet-version: |
            6.0.x
            8.0.x
        
    - name: 🛠️ Install dotnet tools
      run: dotnet tool restore

    - name: 🔨 Build and Test
      run: dotnet tool run dotnet-cake --target=Test --test-run-name=Windows --configuration=Release

    - name: 🔨 Windows Specific Tests
      run: dotnet test --no-build --configuration=Release src/NUnitFramework/windows-tests/windows-tests.csproj

    - name: 📦 Package
      run: dotnet tool run dotnet-cake --target=Package 

    - name: 💾 Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: package

    - name: 💾 Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: Test results (Windows)
        path: test-results
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    - name: Publish nupkg and snupkg to Nuget.org
      run: |
          foreach($file in (Get-ChildItem package -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.PUBLISHNUGET }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
 
